### ISSUE TITLE
Can't start container following README

### ISSUE THREAD

**Issue by michaellopez** [ActiveState/dockron#2]
I am following the README, am I missing something?

```sh
$ docker pull activestate/dockron
Using default tag: latest
latest: Pulling from activestate/dockron

Digest: sha256:b382ca64ac55a196d625469bbb3d66a25a67cf5827c50016ea5777a2259c604c
Status: Image is up to date for activestate/dockron:latest
$ alias dockron="docker run --rm \
       -v $(which docker):/usr/bin/docker:ro \
       -v /var/run/docker.sock:/var/run/docker.sock \
       activestate/dockron"
$ alias
...
alias dockron='docker run --rm        -v /usr/local/bin/docker:/usr/bin/docker:ro        -v /var/run/docker.sock:/var/run/docker.sock        activestate/dockron'
...
$ dockron "0 * * * *" docker run ubuntu /bin/bash -c "echo Hello world"
exec: "/go/src/app/app": stat /go/src/app/app: no such file or directory
Error response from daemon: Cannot start container 4dd6c3ab2beed26296549eb19a00f731a3a55aa977e78d1a0ff4119802b5b740: [8] System error: exec: "/go/src/app/app": stat /go/src/app/app: no such file or directory
```
Looking at the [Dockerfile](https://github.com/ActiveState/dockron/blob/806cd781faaa3cc8c416c3ca5f032dc649c2d130/Dockerfile) and [Makefile](https://github.com/ActiveState/dockron/blob/806cd781faaa3cc8c416c3ca5f032dc649c2d130/Makefile) I'm not seeing how [dockron.go](https://github.com/ActiveState/dockron/blob/940a59b3bdcd81359f298494da3bffb4ff505d35/dockron.go) is ever executed/run? Does `golang:1.3.1-onbuild` do something special?

**Comment by michaellopez** [comment]
I'm not sure why `ENTRYPOINT ["/go/src/app/app"]` is in the `Dockerfile`?

**Comment by ihcsim** [comment]
@michaellopez The `golang:1.3.1-onbuild` image has some `ONBUILD` triggers which copy the content of this project folder into the container `/go/src/app` folder, follow by a call to `go install -v`. The `app` binary is then installed in `$GOPATH/bin`. (You can read more about this on the Golang official Docker Hub [repo](https://hub.docker.com/_/golang/).)

Meanwhile, you can get this to work by replacing `ENTRYPOINT ["/go/src/app/app"]` with `ENTRYPOINT ["/go/bin/app"]`. I will open a PR to fix this.

**Comment by michaellopez** [comment]
@ihcsim Thanks for the info. I did a fork of this repo (https://github.com/weahead/dockron) where I updated the image and changed the Dockerfile to not use `onbuild` given the recommendations in [golangs docker hub repo](https://hub.docker.com/_/golang/)

But I'll see if your PR fixes my issue then I'll be glad to drop my fork as it would no longer be needed.

**Comment by michaellopez** [comment]
@ihcsim When do you think this PR will get merged?

**Comment by ihcsim** [comment]
@michaellopez The PR is merged. I have also updated the Dockerfile to use `golang-1.5.2-onbuild` as its base image, since 1.3 has been [removed](https://github.com/docker-library/golang/commit/7579f7e9257f5615c57f91edc786285fd8ef88ae).

Let me know if this works.

**Comment by michaellopez** [comment]
@ihcsim Works perfect now. Dropped my fork, not needed now. Thanks for your effort!
